### ISSUE TITLE
[BUG] The type or namespace name 'OVRConfigurationTaskException' could not be found

### ISSUE THREAD

**Issue by lknlknim** [oculus-samples/Unity-Movement#138]
### Unity version

6000.4.8f1

### Meta XR Core SDK version

203.0.0

### Which OS are you using?

Windows 11

### Where does the issue occur?

- [x] In Unity Editor
- [ ] In Quest builds

### Description

Compile error when updating Meta XR Core SDK from 201.0.0 to 203.0.0

### Steps to reproduce

Update Meta XR Core SDK to 203.0.0

### Logs

```text
Library\PackageCache\com.meta.xr.sdk.movement@2d2fe7d8ce45\Editor\Native\Scripts\Networking\NGO\NetworkCharacterNGOInstallationRoutine.cs(29,27): error CS0246: The type or namespace name 'OVRConfigurationTaskException' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by kyrylokuzyk-m** [comment]
Thank you! Fixed in https://github.com/oculus-samples/Unity-Movement/commit/6de0c1cfff5d27a927a63cdfb88ab5cd0a084a10
